### ISSUE TITLE
How to install on Raspberry Pi running HomeAssistant OS?

### ISSUE THREAD

**Issue by TonsiTT** [liqi0816/ble2mqtt#1]
Hi,
I managed to get device_id, uuid, local_key, mac_address for my fingerbot. However i'm not sure how to use this library on my raspberry pi running HomeAssistant

Can you tell how to use this?

**Comment by liqi0816** [comment]
Hi,

I just added instructions in readme. Have fun!

**Comment by TonsiTT** [comment]
Thanks alot. 
Just to confirm,
1) i have to first connect it via bluetooth from my Pi to fingerbot right?
2) this will run alongside homeassistant on pi right?

**Comment by liqi0816** [comment]
1. no, this script should be able to handle pairing on its own;
2. depends on your setup. I'm runing it alongside hass but I'm using a conventional ubuntu box, not pi.

**Comment by TonsiTT** [comment]
Are running hass as a docker container or the os version?

**Comment by liqi0816** [comment]
I'm running hass in docker
