### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by cvladan** [liqi0816/ble2mqtt#2]
```
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
```

The problem is I have 

![image](https://user-images.githubusercontent.com/1913156/232900281-5e1adc2a-22bc-46ad-b92d-54ea2b91486a.png)

inside Home Assistant SSH

**Comment by liqi0816** [comment]
Hi,

I just tested with python 3.10 and updated the dependency requirement. Can you try

```bash
pip install --upgrade bleak==0.20.1 PyYAML==6.0 'amqtt>=0.11.0b1' furl==2.1.3 pyee==9.0.4 pycryptodome==3.17
```

The `amqtt>=0.11.0b1` one enables python 3.10.
